---
Name: aws-s3-video-integration
---
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.videoEmbeds:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'videoEmbeds'
